# Generated by Django 4.1.7 on 2023-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datecompleated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
